### ISSUE TITLE
Create the shop page

### ISSUE THREAD

**Issue by ShawnTaylor95** [hilldaniel4/IT-Senior-Capstone-Project#4]
Create shop page and link it with the home page

**Comment by hilldaniel4** [comment]
The shop page is coming along nicely. I have written the baseline HTML and CSS for a set of accordion buttons to display the categories of items in the shop. I have also created a grid within each accordion tab to arrange items, and I have created CSS to display and arrange the items neatly. From here, we will just need to copy and paste card elements to create the remaining items, then type new titles and descriptions. Then we can add images and link them to the items.

**Comment by hilldaniel4** [comment]
Closing this issue, the shop is pretty much done, just need to add the backend functionality. Also there is a weird issue with checkboxes ruining the grid layout somehow? I don't know why, I'll fix it soon though.
